# Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloggingapp-deployment
spec:
  selector:
    matchLabels:
      app: bloggingapp
      track: canary
  replicas: 1
  template:
    metadata:
      labels:
        app: bloggingapp
        track: canary
    spec:
      containers:
        - name: bloggingapp
          image: tnt850910/java-bloggingapp:latest  # Updated image to private DockerHub image
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          livinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 2
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
            requests:
              memory: 64Mi
              cpu: 250m
      imagePullSecrets:
        - name: regcred # Reference to the Docker registry secret
--- 
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: bloggingapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bloggingapp
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
---
# Load Balancer Service

apiVersion: v1
kind: Service
metadata:
  name: bloggingapp-ssvc-canary
spec:
  selector:
    app: bloggingapp
    track: canary
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8081 
  type: LoadBalancer
