name: PR Checks
# This is meant to be copy the functionality of my jenkins build and push

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_REPO }}/${{ github.repository }}:${{ github.sha }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2

    - name: Build
      run: mvn package

    - name: Test
      run: mvn test

    - name: Trivy File System Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        path: '.'
        format: 'table'

    - name: Build & Tag Docker Image
      run: docker build -t ${{ env.DOCKER_IMAGE }} .

    - name: Trivy Docker Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.DOCKER_IMAGE }}
        format: 'table'